### ISSUE TITLE
Suspected deadlock in downloader causes ingest to stop

### ISSUE THREAD

**Issue by markmckenzie** [AusDTO/Splunk-GABQ-Addon#8]

**Comment by monkeypants** [comment]
Evidence that it failed:

1) Has stopped processing data (ingesting). No messages (splunk console, _internal index)
2) looks like there is stuff to go (starting at row, total rows... in internal again).

**Comment by monkeypants** [comment]
Plan:
- Recreate the problem on a second splunk server, get a 14 day trial, get new tokens (or reuse).
- Configure it the same (new input, that one, use the same parameters). They wont interfere.

**Comment by markmckenzie** [comment]
Occurs when pushing an incomplete job back onto the queue from a child process. Using a Manager.JoinableQueue causes other errors.

Refactoring to avoid this problem entirely.

**Comment by markmckenzie** [comment]
"Other problems" were out of memory, resulting in the Manager process being killed. Reducing the queue size and changing the process limit should resolve this.

**Comment by markmckenzie** [comment]
Apparently this didn't resolve it. Refactoring again.
